services:
  postgres:
    image: postgres:16-alpine
    container_name: sally-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sally
    ports:
      - '5432:5432'
    volumes:
      - sally-postgres:/var/lib/postgresql/data
volumes:
  sally-postgres:
