#!/usr/bin/env node
import { confirm, input, password, select } from '@inquirer/prompts'
import crypto from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'
import { spawn } from 'node:child_process'

type InstallMode = 'managed-simple' | 'existing-infra'

function randomSecret(bytes = 24) {
  return crypto.randomBytes(bytes).toString('base64url')
}

function normalizeDomain(value: string) {
  return value.trim().replace(/^https?:\/\//, '').replace(/\/+$/, '')
}

function baseUrlFromDomain(domain: string) {
  return `https://${normalizeDomain(domain)}`
}

function composeForManagedSimple() {
  return `services:
  postgres:
    image: postgres:16-alpine
    container_name: sally-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${'${POSTGRES_USER}'}
      POSTGRES_PASSWORD: ${'${POSTGRES_PASSWORD}'}
      POSTGRES_DB: ${'${POSTGRES_DB}'}
    volumes:
      - sally-postgres:/var/lib/postgresql/data

  api:
    image: ${'${SALLY_API_IMAGE}'}
    container_name: sally-api
    restart: unless-stopped
    env_file: .env
    depends_on:
      - postgres

  web:
    image: ${'${SALLY_WEB_IMAGE}'}
    container_name: sally-web
    restart: unless-stopped
    env_file: .env
    depends_on:
      - api

  caddy:
    image: caddy:2-alpine
    container_name: sally-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - web
      - api

volumes:
  sally-postgres:
  caddy-data:
  caddy-config:
`
}

function composeForExistingInfra() {
  return `services:
  api:
    image: ${'${SALLY_API_IMAGE}'}
    container_name: sally-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "4000:4000"

  web:
    image: ${'${SALLY_WEB_IMAGE}'}
    container_name: sally-web
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - api
`
}

function caddyfile(domain: string) {
  return `${normalizeDomain(domain)} {
  encode gzip zstd

  handle_path /api/* {
    reverse_proxy api:4000
  }

  reverse_proxy web:3000
}
`
}

function envFile(args: {
  mode: InstallMode
  domain: string
  appUrl: string
  imageRegistry: string
  imageTag: string
  superadminEmail: string
  superadminName: string
  smtpHost: string
  smtpPort: string
  smtpUser: string
  smtpPassword: string
  mailFrom: string
  postgresPassword: string
  sessionSecret: string
  appEncryptionKey: string
  bootstrapPassword: string
}) {
  const dbName = 'sally'
  const dbUser = 'postgres'
  const databaseUrl = `postgresql://${dbUser}:${args.postgresPassword}@postgres:5432/${dbName}?schema=public`
  return `# generated by create-sally
SALLY_INSTALL_MODE=${args.mode}
SALLY_URL=${args.appUrl}
APP_BASE_URL=${args.appUrl}
NEXT_PUBLIC_API_BASE_URL=/api
NEXT_PUBLIC_WORKSPACE_SLUG=sally

SALLY_IMAGE_REGISTRY=${args.imageRegistry}
SALLY_IMAGE_TAG=${args.imageTag}
SALLY_API_IMAGE=${args.imageRegistry}/sally-api:${args.imageTag}
SALLY_WEB_IMAGE=${args.imageRegistry}/sally-web:${args.imageTag}

POSTGRES_USER=${dbUser}
POSTGRES_PASSWORD=${args.postgresPassword}
POSTGRES_DB=${dbName}
DATABASE_URL=${databaseUrl}

SESSION_SECRET=${args.sessionSecret}
APP_ENCRYPTION_KEY=${args.appEncryptionKey}

SUPERADMIN_EMAIL=${args.superadminEmail}
SUPERADMIN_NAME=${args.superadminName}
BOOTSTRAP_SUPERADMIN_PASSWORD=${args.bootstrapPassword}

SMTP_HOST=${args.smtpHost}
SMTP_PORT=${args.smtpPort}
SMTP_USER=${args.smtpUser}
SMTP_PASSWORD=${args.smtpPassword}
MAIL_FROM=${args.mailFrom}

# optional compatibility / provider-level SMTP URL if needed later
# SMTP_URL=smtps://${args.smtpUser}:${args.smtpPassword}@${args.smtpHost}:${args.smtpPort}
`
}

function setupNotes(mode: InstallMode, bootstrapPassword: string, targetDir: string, appUrl: string) {
  const common = `sally_ installer scaffold created.

Location:
- ${targetDir}

Next steps:
- review .env
- make sure your domain points to this server
- start the stack with docker compose
- run bootstrap + health verification

Generated temporary superadmin password:
- ${bootstrapPassword}

Planned login URL:
- ${appUrl}
`
  if (mode === 'managed-simple') {
    return `${common}
Managed-simple files:
- docker-compose.yml
- Caddyfile
- .env
`
  }
  return `${common}
Existing-infra files:
- docker-compose.yml
- .env

Expected from your infra:
- reverse proxy routing to web/api
- TLS termination
- optional external DB adaptation if you do not want local Postgres
`
}

async function runCommand(command: string, args: string[], cwd: string) {
  await new Promise<void>((resolve, reject) => {
    const child = spawn(command, args, { cwd, stdio: 'inherit', shell: false })
    child.on('exit', (code) => {
      if (code === 0) resolve()
      else reject(new Error(`${command} ${args.join(' ')} failed with exit code ${code ?? 'unknown'}`))
    })
    child.on('error', reject)
  })
}

async function waitForHealth(url: string, label: string, attempts = 30, delayMs = 2000) {
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      const response = await fetch(url)
      if (response.ok) return
    } catch {}
    await new Promise((resolve) => setTimeout(resolve, delayMs))
  }
  throw new Error(`${label} did not become healthy at ${url}`)
}

async function runInstallerCommands(mode: InstallMode, targetDir: string, appUrl: string) {
  await runCommand('docker', ['compose', 'up', '-d'], targetDir)
  await runCommand('docker', ['compose', 'exec', '-T', 'api', 'sh', '-lc', 'pnpm --filter @sally/db prisma db push --schema packages/db/prisma/schema.prisma'], targetDir)
  await runCommand('docker', ['compose', 'exec', '-T', 'api', 'node', 'apps/api/dist/bootstrap.js'], targetDir)
  if (mode === 'managed-simple') {
    await waitForHealth(`${appUrl}/api/health`, 'API')
    await waitForHealth(appUrl, 'Web app')
  } else {
    await waitForHealth('http://127.0.0.1:4000/health', 'API')
    await waitForHealth('http://127.0.0.1:3000', 'Web app')
  }
}

async function main() {
  const mode = await select<InstallMode>({
    message: 'How do you want to install sally_?',
    choices: [
      { name: 'managed-simple — sally_ sets up Docker + Postgres + HTTPS', value: 'managed-simple' },
      { name: 'existing-infra — I already have infrastructure and want sally_ to fit into it', value: 'existing-infra' },
    ],
  })

  const defaultDir = path.resolve(process.cwd(), 'sally-instance')
  const targetDir = path.resolve(await input({ message: 'Where should the installer write the instance files?', default: defaultDir }))
  const domain = normalizeDomain(await input({ message: 'Domain for this sally_ instance (example: sally.example.com)' }))
  const appUrl = baseUrlFromDomain(domain)
  const imageRegistry = await input({ message: 'Container image registry / namespace', default: 'ghcr.io/use-sally' })
  const imageTag = await input({ message: 'Container image tag', default: 'latest' })
  const superadminEmail = await input({ message: 'Superadmin email' })
  const superadminName = await input({ message: 'Superadmin name', default: 'Admin' })
  const smtpHost = await input({ message: 'SMTP host' })
  const smtpPort = await input({ message: 'SMTP port', default: '587' })
  const smtpUser = await input({ message: 'SMTP username' })
  const smtpPassword = await password({ message: 'SMTP password' })
  const mailFrom = await input({ message: 'MAIL_FROM address', default: `no-reply@${domain}` })

  const postgresPassword = randomSecret(24)
  const sessionSecret = randomSecret(32)
  const appEncryptionKey = randomSecret(32)
  const bootstrapPassword = randomSecret(16)

  await fs.mkdir(targetDir, { recursive: true })
  await fs.writeFile(path.join(targetDir, '.env'), envFile({ mode, domain, appUrl, imageRegistry, imageTag, superadminEmail, superadminName, smtpHost, smtpPort, smtpUser, smtpPassword, mailFrom, postgresPassword, sessionSecret, appEncryptionKey, bootstrapPassword }))
  await fs.writeFile(path.join(targetDir, 'docker-compose.yml'), mode === 'managed-simple' ? composeForManagedSimple() : composeForExistingInfra())
  if (mode === 'managed-simple') {
    await fs.writeFile(path.join(targetDir, 'Caddyfile'), caddyfile(domain))
  }
  await fs.writeFile(path.join(targetDir, 'SETUP_NOTES.txt'), setupNotes(mode, bootstrapPassword, targetDir, appUrl))

  console.log(setupNotes(mode, bootstrapPassword, targetDir, appUrl))

  const runCompose = await confirm({ message: 'Run docker compose setup now?', default: false })
  if (runCompose) {
    await runInstallerCommands(mode, targetDir, appUrl)
    console.log(`\nsally_ setup completed. Open: ${appUrl}`)
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error))
  process.exit(1)
})
