#!/usr/bin/env node
import { confirm, input, password, select } from '@inquirer/prompts'
import crypto from 'node:crypto'
import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { spawn } from 'node:child_process'

type InstallMode = 'managed-simple' | 'existing-infra'

const color = {
  reset: '\x1b[0m',
  dim: '\x1b[2m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  brightYellow: '\x1b[93m',
  brightGreen: '\x1b[92m',
  red: '\x1b[31m',
  cyan: '\x1b[36m',
}

function paint(text: string, tone: string) {
  return `${tone}${text}${color.reset}`
}

function section(title: string) {
  console.log(`\n${paint(title, color.brightYellow)}`)
}

function banner() {
  console.log(paint('S A L L Y  :::::::  I N S T A L L E R', color.brightGreen))
  console.log(paint('clean deploy flow for sally_', color.dim))
}

function randomSecret(bytes = 24) {
  return crypto.randomBytes(bytes).toString('base64url')
}

function normalizeDomain(value: string) {
  return value.trim().replace(/^https?:\/\//, '').replace(/\/+$/, '')
}

function baseUrlFromDomain(domain: string) {
  return `https://${normalizeDomain(domain)}`
}

function slugifyWorkspaceName(value: string) {
  const slug = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')

  return slug || 'workspace'
}

function composeForManagedSimple() {
  return `services:
  postgres:
    image: postgres:16-alpine
    container_name: sally-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${'${POSTGRES_USER}'}
      POSTGRES_PASSWORD: ${'${POSTGRES_PASSWORD}'}
      POSTGRES_DB: ${'${POSTGRES_DB}'}
    volumes:
      - sally-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 2s
      timeout: 5s
      retries: 20

  api:
    image: ${'${SALLY_API_IMAGE}'}
    container_name: sally-api
    restart: unless-stopped
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy

  web:
    image: ${'${SALLY_WEB_IMAGE}'}
    container_name: sally-web
    restart: unless-stopped
    env_file: .env
    depends_on:
      - api

  caddy:
    image: caddy:2-alpine
    container_name: sally-caddy
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - web
      - api

volumes:
  sally-postgres:
  caddy-data:
  caddy-config:
`
}

function composeForExistingInfra() {
  return `services:
  postgres:
    image: postgres:16-alpine
    container_name: sally-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${'${POSTGRES_USER}'}
      POSTGRES_PASSWORD: ${'${POSTGRES_PASSWORD}'}
      POSTGRES_DB: ${'${POSTGRES_DB}'}
    volumes:
      - sally-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 2s
      timeout: 5s
      retries: 20

  api:
    image: ${'${SALLY_API_IMAGE}'}
    container_name: sally-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy

  web:
    image: ${'${SALLY_WEB_IMAGE}'}
    container_name: sally-web
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  sally-postgres:
`
}

function caddyfile(domain: string) {
  return `{
  email {$CADDY_ACME_EMAIL}
}

${normalizeDomain(domain)} {
  encode gzip zstd

  handle_path /api/* {
    reverse_proxy api:4000
  }

  reverse_proxy web:3000
}
`
}

function envFile(args: {
  mode: InstallMode
  domain: string
  appUrl: string
  imageTag: string
  workspaceName: string
  workspaceSlug: string
  superadminEmail: string
  superadminName: string
  smtpConfigured: boolean
  smtpHost: string
  smtpPort: string
  smtpUser: string
  smtpPassword: string
  mailFrom: string
  caddyAcmeEmail?: string
  postgresPassword: string
  sessionSecret: string
  appEncryptionKey: string
  bootstrapPassword: string
}) {
  const dbName = 'sally'
  const dbUser = 'postgres'
  const databaseUrl = `postgresql://${dbUser}:${args.postgresPassword}@postgres:5432/${dbName}?schema=public`
  return `# generated by create-sally
SALLY_INSTALL_MODE=${args.mode}
SALLY_URL=${args.appUrl}
APP_BASE_URL=${args.appUrl}
NEXT_PUBLIC_API_BASE_URL=/api
NEXT_PUBLIC_WORKSPACE_SLUG=${args.workspaceSlug}
SALLY_WORKSPACE_NAME=${args.workspaceName}
SALLY_WORKSPACE_SLUG=${args.workspaceSlug}

SALLY_IMAGE_REGISTRY=ghcr.io/use-sally
SALLY_IMAGE_TAG=${args.imageTag}
SALLY_API_IMAGE=ghcr.io/use-sally/sally-api:${args.imageTag}
SALLY_WEB_IMAGE=ghcr.io/use-sally/sally-web:${args.imageTag}

POSTGRES_USER=${dbUser}
POSTGRES_PASSWORD=${args.postgresPassword}
POSTGRES_DB=${dbName}
DATABASE_URL=${databaseUrl}

SESSION_SECRET=${args.sessionSecret}
APP_ENCRYPTION_KEY=${args.appEncryptionKey}

SUPERADMIN_EMAIL=${args.superadminEmail}
SUPERADMIN_NAME=${args.superadminName}
BOOTSTRAP_SUPERADMIN_PASSWORD=${args.bootstrapPassword}

SMTP_HOST=${args.smtpHost}
SMTP_PORT=${args.smtpPort}
SMTP_USER=${args.smtpUser}
SMTP_PASSWORD=${args.smtpPassword}
MAIL_FROM=${args.mailFrom}
CADDY_ACME_EMAIL=${args.caddyAcmeEmail ?? ''}

# email setup status from installer
SMTP_CONFIGURED=${args.smtpConfigured ? 'true' : 'false'}

# optional compatibility / provider-level SMTP URL if needed later
# SMTP_URL=smtps://${args.smtpUser}:${args.smtpPassword}@${args.smtpHost}:${args.smtpPort}
`
}

function setupNotes(mode: InstallMode, bootstrapPassword: string, targetDir: string, appUrl: string, smtpConfigured: boolean) {
  const emailNotes = smtpConfigured
    ? 'Email is configured in .env.\n'
    : `Email setup is still required for invites, password resets, and notifications.\nUpdate SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, and MAIL_FROM in .env, then run docker compose up -d.\n`

  if (mode === 'managed-simple') {
    return `Sally instance files:\n- ${targetDir}\n\nManaged-simple files:\n- docker-compose.yml\n- Caddyfile\n- .env\n\nLogin URL:\n- ${appUrl}\n\nSuperadmin password:\n- ${bootstrapPassword}\n\n${emailNotes}`
  }

  return `Sally instance files:\n- ${targetDir}\n\nExisting-infra files:\n- docker-compose.yml\n- .env\n\nPublic app URL after your reverse proxy / TLS is configured:\n- ${appUrl}\n\nSuperadmin password:\n- ${bootstrapPassword}\n\n${emailNotes}`
}

async function runCommand(command: string, args: string[], cwd: string, options?: { quiet?: boolean }) {
  await new Promise<void>((resolve, reject) => {
    const child = spawn(command, args, { cwd, stdio: options?.quiet ? ['ignore', 'pipe', 'pipe'] : 'inherit', shell: false })
    let stderr = ''

    if (options?.quiet) {
      child.stdout?.on('data', () => {})
      child.stderr?.on('data', (chunk) => {
        stderr += String(chunk)
      })
    }

    child.on('exit', (code) => {
      if (code === 0) resolve()
      else reject(new Error(stderr.trim() || `${command} ${args.join(' ')} failed with exit code ${code ?? 'unknown'}`))
    })
    child.on('error', reject)
  })
}

async function runCommandCapture(command: string, args: string[], cwd?: string) {
  return await new Promise<string>((resolve, reject) => {
    const child = spawn(command, args, { cwd, stdio: ['ignore', 'pipe', 'pipe'], shell: false })
    let stdout = ''
    let stderr = ''
    child.stdout.on('data', (chunk) => {
      stdout += String(chunk)
    })
    child.stderr.on('data', (chunk) => {
      stderr += String(chunk)
    })
    child.on('exit', (code) => {
      if (code === 0) resolve(stdout)
      else reject(new Error(stderr.trim() || `${command} ${args.join(' ')} failed with exit code ${code ?? 'unknown'}`))
    })
    child.on('error', reject)
  })
}

async function detectServerIpv4() {
  const candidates = [
    ['dig', ['+short', 'myip.opendns.com', '@resolver1.opendns.com']],
    ['sh', ['-lc', 'curl -4fsSL https://api.ipify.org || curl -4fsSL https://ifconfig.me']],
  ] as const

  for (const [command, args] of candidates) {
    try {
      const output = (await runCommandCapture(command, Array.from(args))).trim().split(/\s+/).find(Boolean)
      if (output && /^\d+\.\d+\.\d+\.\d+$/.test(output)) return output
    } catch {}
  }

  const interfaces = os.networkInterfaces()
  for (const entries of Object.values(interfaces)) {
    for (const entry of entries ?? []) {
      if (entry.family === 'IPv4' && !entry.internal) return entry.address
    }
  }

  throw new Error('Could not determine the server public IPv4 address for DNS verification.')
}

async function resolveDomainIpv4(domain: string) {
  try {
    const output = await runCommandCapture('dig', ['+short', normalizeDomain(domain), 'A'])
    return output.split(/\r?\n/).map((line) => line.trim()).filter((line) => /^\d+\.\d+\.\d+\.\d+$/.test(line))
  } catch {
    return []
  }
}

async function verifyManagedDomainPointsHere(domain: string) {
  const serverIp = await detectServerIpv4()
  const resolvedIps = await resolveDomainIpv4(domain)

  if (resolvedIps.length === 0) {
    throw new Error(`Domain check failed: ${domain} does not currently resolve to an A record. Point it to ${serverIp} and run the installer again.`)
  }

  if (!resolvedIps.includes(serverIp)) {
    throw new Error(`Domain check failed: ${domain} resolves to ${resolvedIps.join(', ')}, but this server is ${serverIp}. Point the domain to this server first, then rerun the installer.`)
  }

  console.log(paint(`DNS OK  ${domain} -> ${serverIp}`, color.green))
}

function printWelcome(mode: InstallMode, appUrl: string, superadminEmail: string, bootstrapPassword: string) {
  console.log('')
  console.log(paint('W E L C O M E  :::::::  T O  :::::::  S A L L Y', color.brightGreen))
  if (mode === 'managed-simple') {
    console.log(`${paint('URL', color.brightYellow)}: ${appUrl}`)
  } else {
    console.log(`${paint('URL', color.brightYellow)}: ${appUrl} ${paint('(after your reverse proxy / TLS is configured)', color.dim)}`)
    console.log(`${paint('LOCAL', color.brightYellow)}: http://127.0.0.1:3000`)
    console.log(`${paint('API', color.brightYellow)}: http://127.0.0.1:4000`)
  }
  console.log(`${paint('USER', color.brightYellow)}: ${superadminEmail}`)
  console.log(`${paint('PASSWORD', color.brightYellow)}: ${bootstrapPassword}`)
}

async function hasCommand(command: string) {
  try {
    await runCommandCapture('sh', ['-lc', `command -v ${command}`])
    return true
  } catch {
    return false
  }
}

async function ensureDockerInstalled() {
  const hasDocker = await hasCommand('docker')
  const hasCompose = hasDocker
    ? await new Promise<boolean>((resolve) => {
      const child = spawn('docker', ['compose', 'version'], { stdio: 'ignore', shell: false })
      child.on('exit', (code) => resolve(code === 0))
      child.on('error', () => resolve(false))
    })
    : false

  if (hasDocker && hasCompose) {
    console.log(paint('Docker OK', color.green))
    return
  }

  if (process.platform !== 'linux') {
    throw new Error('Docker is missing and automatic installation is only supported by this installer on Linux right now.')
  }

  section('Installing Docker')
  console.log(paint('Docker or Docker Compose is missing. Sally will install Docker now.', color.yellow))
  await runCommand('sh', ['-lc', 'curl -fsSL https://get.docker.com | sh'], process.cwd())
  await runCommand('sh', ['-lc', 'systemctl enable --now docker 2>/dev/null || service docker start 2>/dev/null || true'], process.cwd())

  const dockerInstalled = await hasCommand('docker')
  const composeInstalled = dockerInstalled
    ? await new Promise<boolean>((resolve) => {
      const child = spawn('docker', ['compose', 'version'], { stdio: 'ignore', shell: false })
      child.on('exit', (code) => resolve(code === 0))
      child.on('error', () => resolve(false))
    })
    : false

  if (!dockerInstalled || !composeInstalled) {
    throw new Error('Docker installation did not complete successfully. Install Docker + Docker Compose manually, then rerun create-sally.')
  }

  console.log(paint('Docker installed successfully', color.green))
}

async function installAndScaffoldMcp(targetDir: string, appUrl: string) {
  const mcpDir = path.join(targetDir, 'mcp')
  await fs.mkdir(mcpDir, { recursive: true })

  section('Installing Sally MCP')
  await runCommand('npm', ['install', '-g', 'sally-mcp@latest'], targetDir)

  const envExample = `SALLY_URL=${appUrl}
SALLY_USER_API_KEY=replace-with-your-personal-sally-api-key
# Optional advanced restriction:
# SALLY_WORKSPACE_SLUG=your-workspace-slug
`

  const runScript = `#!/usr/bin/env sh
set -eu

if [ ! -f "$(dirname "$0")/.env" ]; then
  echo "Missing $(dirname "$0")/.env"
  echo "Copy .env.example to .env and add your personal Sally API key first."
  exit 1
fi

set -a
. "$(dirname "$0")/.env"
set +a

exec sally-mcp
`

  const openClawConfig = `{
  "mcpServers": {
    "sally": {
      "command": "sally-mcp",
      "env": {
        "SALLY_URL": "${appUrl}",
        "SALLY_USER_API_KEY": "replace-with-your-personal-sally-api-key"
      }
    }
  }
}
`

  const setupText = `Sally MCP scaffold created.

Location:
- ${mcpDir}

Next steps:
1. copy .env.example to .env
2. log into Sally
3. create a personal API key in Sally
4. paste that key into SALLY_USER_API_KEY
5. optional: set SALLY_WORKSPACE_SLUG if you want this MCP server pinned to one workspace
6. run ./run-mcp.sh or use the example client config
`

  await fs.writeFile(path.join(mcpDir, '.env.example'), envExample)
  await fs.writeFile(path.join(mcpDir, 'run-mcp.sh'), runScript)
  await fs.writeFile(path.join(mcpDir, 'openclaw.example.json'), openClawConfig)
  await fs.writeFile(path.join(mcpDir, 'MCP_SETUP.txt'), setupText)
  await fs.chmod(path.join(mcpDir, 'run-mcp.sh'), 0o755)

  console.log(paint(`Sally MCP ready at ${mcpDir}`, color.green))
}

async function waitForHealth(url: string, label: string, attempts = 30, delayMs = 2000) {
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      const response = await fetch(url)
      if (response.ok) return
    } catch {}
    await new Promise((resolve) => setTimeout(resolve, delayMs))
  }
  throw new Error(`${label} did not become healthy at ${url}`)
}

async function waitForPostgres(targetDir: string, attempts = 30, delayMs = 2000) {
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      await runCommand('docker', ['compose', 'exec', '-T', 'postgres', 'pg_isready', '-U', 'postgres'], targetDir)
      return
    } catch {}
    await new Promise((resolve) => setTimeout(resolve, delayMs))
  }
  throw new Error('Postgres did not become ready in time')
}

async function runInstallerCommands(mode: InstallMode, targetDir: string, appUrl: string) {
  section('Pulling fresh Sally images')
  await runCommand('docker', ['compose', 'pull', 'api', 'web'], targetDir)

  section('Starting database')
  await runCommand('docker', ['compose', 'up', '-d', 'postgres'], targetDir)
  await waitForPostgres(targetDir)

  section('Applying database schema')
  await runCommand('docker', ['compose', 'run', '--rm', 'api', 'sh', '-lc', 'cd /app/packages/db && pnpm exec prisma db push --schema prisma/schema.prisma'], targetDir)

  section('Bootstrapping superadmin')
  await runCommand('docker', ['compose', 'run', '--rm', 'api', 'node', 'apps/api/dist/bootstrap.js'], targetDir, { quiet: true })

  if (mode === 'managed-simple') {
    section('Starting Sally services')
    await runCommand('docker', ['compose', 'up', '-d', '--force-recreate', 'api', 'web', 'caddy'], targetDir)
    await waitForHealth(`${appUrl}/api/health`, 'API')
    await waitForHealth(appUrl, 'Web app')
  } else {
    section('Starting Sally services')
    await runCommand('docker', ['compose', 'up', '-d', '--force-recreate', 'api', 'web'], targetDir)
    await waitForHealth('http://127.0.0.1:4000/health', 'API')
    await waitForHealth('http://127.0.0.1:3000', 'Web app')
  }
}

async function main() {
  banner()
  await ensureDockerInstalled()

  const mode = await select<InstallMode>({
    message: 'How do you want to install sally_?',
    choices: [
      { name: 'managed-simple — sally_ sets up Docker + Postgres + HTTPS', value: 'managed-simple' },
      { name: 'existing-infra — I already have infrastructure and want sally_ to fit into it', value: 'existing-infra' },
    ],
  })

  const defaultDir = '/opt/sally-instance'
  const targetDir = path.resolve(await input({ message: 'Where should the installer write the instance files?', default: defaultDir }))
  const domain = normalizeDomain(await input({ message: 'Domain for this sally_ instance (example: sally.example.com)' }))
  const appUrl = baseUrlFromDomain(domain)

  if (mode === 'managed-simple') {
    section('Checking DNS')
    await verifyManagedDomainPointsHere(domain)
  }

  const imageTag = await input({ message: 'Sally version', default: 'latest' })
  const workspaceName = await input({ message: 'First workspace name', default: 'Operations' })
  const workspaceSlug = slugifyWorkspaceName(workspaceName)
  const superadminEmail = await input({ message: 'Superadmin email' })
  const superadminName = await input({ message: 'Superadmin name', default: 'Admin' })
  const caddyAcmeEmail = mode === 'managed-simple'
    ? await input({ message: 'ACME / TLS contact email', default: superadminEmail })
    : ''

  const emailSetupMode = await select<'configure-now' | 'configure-later'>({
    message: 'Email setup is strongly recommended. Without it, sally_ cannot send invites, password resets, or notification emails. How do you want to continue?',
    choices: [
      { name: 'Configure email now (recommended)', value: 'configure-now' },
      { name: 'I will configure email later in .env and restart the stack', value: 'configure-later' },
    ],
  })

  let smtpConfigured = emailSetupMode === 'configure-now'
  let smtpHost = 'smtp.disabled.invalid'
  let smtpPort = '587'
  let smtpUser = 'disabled'
  let smtpPassword = 'disabled'
  let mailFrom = `no-reply@${domain}`

  if (smtpConfigured) {
    smtpHost = await input({ message: 'SMTP host' })
    smtpPort = await input({ message: 'SMTP port', default: '587' })
    smtpUser = await input({ message: 'SMTP username' })
    smtpPassword = await password({ message: 'SMTP password' })
    mailFrom = await input({ message: 'MAIL_FROM address', default: `no-reply@${domain}` })
  } else {
    const confirmLater = await confirm({
      message: 'I understand that invites, password resets, and notification emails will not work until I update SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, and MAIL_FROM in .env and restart the stack.',
      default: false,
    })

    if (!confirmLater) {
      throw new Error('Email setup was skipped without confirmation. Restart the installer and configure email now, or confirm the manual-later path.')
    }
  }

  const postgresPassword = randomSecret(24)
  const sessionSecret = randomSecret(32)
  const appEncryptionKey = randomSecret(32)
  const bootstrapPassword = randomSecret(16)

  await fs.mkdir(targetDir, { recursive: true })
  await fs.writeFile(path.join(targetDir, '.env'), envFile({ mode, domain, appUrl, imageTag, workspaceName, workspaceSlug, superadminEmail, superadminName, smtpConfigured, smtpHost, smtpPort, smtpUser, smtpPassword, mailFrom, caddyAcmeEmail, postgresPassword, sessionSecret, appEncryptionKey, bootstrapPassword }))
  await fs.writeFile(path.join(targetDir, 'docker-compose.yml'), mode === 'managed-simple' ? composeForManagedSimple() : composeForExistingInfra())
  if (mode === 'managed-simple') {
    await fs.writeFile(path.join(targetDir, 'Caddyfile'), caddyfile(domain))
  }
  await fs.writeFile(path.join(targetDir, 'SETUP_NOTES.txt'), setupNotes(mode, bootstrapPassword, targetDir, appUrl, smtpConfigured))

  await runInstallerCommands(mode, targetDir, appUrl)
  await installAndScaffoldMcp(targetDir, appUrl)
  printWelcome(mode, appUrl, superadminEmail, bootstrapPassword)
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error))
  process.exit(1)
})
