#!/usr/bin/env node
import { confirm, input, password, select } from '@inquirer/prompts'
import crypto from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'
import { spawn } from 'node:child_process'

type InstallMode = 'managed-simple' | 'existing-infra'

function randomSecret(bytes = 24) {
  return crypto.randomBytes(bytes).toString('base64url')
}

function normalizeDomain(value: string) {
  return value.trim().replace(/^https?:\/\//, '').replace(/\/+$/, '')
}

function baseUrlFromDomain(domain: string) {
  return `https://${normalizeDomain(domain)}`
}

function composeForManagedSimple() {
  return `services:
  postgres:
    image: postgres:16-alpine
    container_name: sally-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${'${POSTGRES_USER}'}
      POSTGRES_PASSWORD: ${'${POSTGRES_PASSWORD}'}
      POSTGRES_DB: ${'${POSTGRES_DB}'}
    volumes:
      - sally-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 2s
      timeout: 5s
      retries: 20

  api:
    image: ${'${SALLY_API_IMAGE}'}
    container_name: sally-api
    restart: unless-stopped
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy

  web:
    image: ${'${SALLY_WEB_IMAGE}'}
    container_name: sally-web
    restart: unless-stopped
    env_file: .env
    depends_on:
      - api

  caddy:
    image: caddy:2-alpine
    container_name: sally-caddy
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - web
      - api

volumes:
  sally-postgres:
  caddy-data:
  caddy-config:
`
}

function composeForExistingInfra() {
  return `services:
  postgres:
    image: postgres:16-alpine
    container_name: sally-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${'${POSTGRES_USER}'}
      POSTGRES_PASSWORD: ${'${POSTGRES_PASSWORD}'}
      POSTGRES_DB: ${'${POSTGRES_DB}'}
    volumes:
      - sally-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 2s
      timeout: 5s
      retries: 20

  api:
    image: ${'${SALLY_API_IMAGE}'}
    container_name: sally-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy

  web:
    image: ${'${SALLY_WEB_IMAGE}'}
    container_name: sally-web
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  sally-postgres:
`
}

function caddyfile(domain: string) {
  return `{
  email {$CADDY_ACME_EMAIL}
}

${normalizeDomain(domain)} {
  encode gzip zstd

  handle_path /api/* {
    reverse_proxy api:4000
  }

  reverse_proxy web:3000
}
`
}

function envFile(args: {
  mode: InstallMode
  domain: string
  appUrl: string
  imageRegistry: string
  imageTag: string
  superadminEmail: string
  superadminName: string
  smtpConfigured: boolean
  smtpHost: string
  smtpPort: string
  smtpUser: string
  smtpPassword: string
  mailFrom: string
  caddyAcmeEmail?: string
  postgresPassword: string
  sessionSecret: string
  appEncryptionKey: string
  bootstrapPassword: string
}) {
  const dbName = 'sally'
  const dbUser = 'postgres'
  const databaseUrl = `postgresql://${dbUser}:${args.postgresPassword}@postgres:5432/${dbName}?schema=public`
  return `# generated by create-sally
SALLY_INSTALL_MODE=${args.mode}
SALLY_URL=${args.appUrl}
APP_BASE_URL=${args.appUrl}
NEXT_PUBLIC_API_BASE_URL=/api
NEXT_PUBLIC_WORKSPACE_SLUG=sally

SALLY_IMAGE_REGISTRY=${args.imageRegistry}
SALLY_IMAGE_TAG=${args.imageTag}
SALLY_API_IMAGE=${args.imageRegistry}/sally-api:${args.imageTag}
SALLY_WEB_IMAGE=${args.imageRegistry}/sally-web:${args.imageTag}

POSTGRES_USER=${dbUser}
POSTGRES_PASSWORD=${args.postgresPassword}
POSTGRES_DB=${dbName}
DATABASE_URL=${databaseUrl}

SESSION_SECRET=${args.sessionSecret}
APP_ENCRYPTION_KEY=${args.appEncryptionKey}

SUPERADMIN_EMAIL=${args.superadminEmail}
SUPERADMIN_NAME=${args.superadminName}
BOOTSTRAP_SUPERADMIN_PASSWORD=${args.bootstrapPassword}

SMTP_HOST=${args.smtpHost}
SMTP_PORT=${args.smtpPort}
SMTP_USER=${args.smtpUser}
SMTP_PASSWORD=${args.smtpPassword}
MAIL_FROM=${args.mailFrom}
CADDY_ACME_EMAIL=${args.caddyAcmeEmail ?? ''}

# email setup status from installer
SMTP_CONFIGURED=${args.smtpConfigured ? 'true' : 'false'}

# optional compatibility / provider-level SMTP URL if needed later
# SMTP_URL=smtps://${args.smtpUser}:${args.smtpPassword}@${args.smtpHost}:${args.smtpPort}
`
}

function setupNotes(mode: InstallMode, bootstrapPassword: string, targetDir: string, appUrl: string, smtpConfigured: boolean) {
  const emailNotes = smtpConfigured
    ? `Email:
- SMTP is configured in .env
`
    : `Email still required:
- sally_ will install, but it will not send invites, password resets, or notification emails until you finish email setup.
- update these .env values:
  - SMTP_HOST
  - SMTP_PORT
  - SMTP_USER
  - SMTP_PASSWORD
  - MAIL_FROM
- then restart the stack with: docker compose up -d
`

  if (mode === 'managed-simple') {
    return `sally_ installer scaffold created.

Location:
- ${targetDir}

Next steps:
- review .env
- make sure your domain points to this server
- start the stack with docker compose
- run bootstrap + health verification

Generated temporary superadmin password:
- ${bootstrapPassword}

Planned login URL:
- ${appUrl}

Managed-simple files:
- docker-compose.yml
- Caddyfile
- .env

${emailNotes}`
  }

  return `sally_ installer scaffold created.

Location:
- ${targetDir}

Next steps:
- review .env
- start the stack with docker compose
- run bootstrap + health verification
- put your reverse proxy / TLS in front of web:3000 and api:4000

Generated temporary superadmin password:
- ${bootstrapPassword}

Planned public app URL (after your infra is configured):
- ${appUrl}

Existing-infra files:
- docker-compose.yml
- .env

Expected from your infra:
- reverse proxy routing to web/api
- TLS termination
- optional external DB adaptation if you do not want local Postgres

${emailNotes}`
}

async function runCommand(command: string, args: string[], cwd: string) {
  await new Promise<void>((resolve, reject) => {
    const child = spawn(command, args, { cwd, stdio: 'inherit', shell: false })
    child.on('exit', (code) => {
      if (code === 0) resolve()
      else reject(new Error(`${command} ${args.join(' ')} failed with exit code ${code ?? 'unknown'}`))
    })
    child.on('error', reject)
  })
}

async function waitForHealth(url: string, label: string, attempts = 30, delayMs = 2000) {
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      const response = await fetch(url)
      if (response.ok) return
    } catch {}
    await new Promise((resolve) => setTimeout(resolve, delayMs))
  }
  throw new Error(`${label} did not become healthy at ${url}`)
}

async function waitForPostgres(targetDir: string, attempts = 30, delayMs = 2000) {
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    try {
      await runCommand('docker', ['compose', 'exec', '-T', 'postgres', 'pg_isready', '-U', 'postgres'], targetDir)
      return
    } catch {}
    await new Promise((resolve) => setTimeout(resolve, delayMs))
  }
  throw new Error('Postgres did not become ready in time')
}

async function runInstallerCommands(mode: InstallMode, targetDir: string, appUrl: string) {
  await runCommand('docker', ['compose', 'up', '-d', 'postgres'], targetDir)
  await waitForPostgres(targetDir)
  await runCommand('docker', ['compose', 'run', '--rm', 'api', 'sh', '-lc', 'cd /app/packages/db && pnpm exec prisma db push --schema prisma/schema.prisma'], targetDir)
  await runCommand('docker', ['compose', 'run', '--rm', 'api', 'node', 'apps/api/dist/bootstrap.js'], targetDir)

  if (mode === 'managed-simple') {
    await runCommand('docker', ['compose', 'up', '-d', 'api', 'web', 'caddy'], targetDir)
    await waitForHealth(`${appUrl}/api/health`, 'API')
    await waitForHealth(appUrl, 'Web app')
  } else {
    await runCommand('docker', ['compose', 'up', '-d', 'api', 'web'], targetDir)
    await waitForHealth('http://127.0.0.1:4000/health', 'API')
    await waitForHealth('http://127.0.0.1:3000', 'Web app')
  }
}

async function main() {
  const mode = await select<InstallMode>({
    message: 'How do you want to install sally_?',
    choices: [
      { name: 'managed-simple — sally_ sets up Docker + Postgres + HTTPS', value: 'managed-simple' },
      { name: 'existing-infra — I already have infrastructure and want sally_ to fit into it', value: 'existing-infra' },
    ],
  })

  const defaultDir = path.resolve(process.cwd(), 'sally-instance')
  const targetDir = path.resolve(await input({ message: 'Where should the installer write the instance files?', default: defaultDir }))
  const domain = normalizeDomain(await input({ message: 'Domain for this sally_ instance (example: sally.example.com)' }))
  const appUrl = baseUrlFromDomain(domain)
  const imageRegistry = await input({ message: 'Container image registry / namespace', default: 'ghcr.io/use-sally' })
  const imageTag = await input({ message: 'Container image tag', default: 'latest' })
  const superadminEmail = await input({ message: 'Superadmin email' })
  const superadminName = await input({ message: 'Superadmin name', default: 'Admin' })
  const caddyAcmeEmail = mode === 'managed-simple'
    ? await input({ message: 'ACME / TLS contact email', default: superadminEmail })
    : ''

  const emailSetupMode = await select<'configure-now' | 'configure-later'>({
    message: 'Email setup is strongly recommended. Without it, sally_ cannot send invites, password resets, or notification emails. How do you want to continue?',
    choices: [
      { name: 'Configure email now (recommended)', value: 'configure-now' },
      { name: 'I will configure email later in .env and restart the stack', value: 'configure-later' },
    ],
  })

  let smtpConfigured = emailSetupMode === 'configure-now'
  let smtpHost = 'smtp.disabled.invalid'
  let smtpPort = '587'
  let smtpUser = 'disabled'
  let smtpPassword = 'disabled'
  let mailFrom = `no-reply@${domain}`

  if (smtpConfigured) {
    smtpHost = await input({ message: 'SMTP host' })
    smtpPort = await input({ message: 'SMTP port', default: '587' })
    smtpUser = await input({ message: 'SMTP username' })
    smtpPassword = await password({ message: 'SMTP password' })
    mailFrom = await input({ message: 'MAIL_FROM address', default: `no-reply@${domain}` })
  } else {
    const confirmLater = await confirm({
      message: 'I understand that invites, password resets, and notification emails will not work until I update SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, and MAIL_FROM in .env and restart the stack.',
      default: false,
    })

    if (!confirmLater) {
      throw new Error('Email setup was skipped without confirmation. Restart the installer and configure email now, or confirm the manual-later path.')
    }
  }

  const postgresPassword = randomSecret(24)
  const sessionSecret = randomSecret(32)
  const appEncryptionKey = randomSecret(32)
  const bootstrapPassword = randomSecret(16)

  await fs.mkdir(targetDir, { recursive: true })
  await fs.writeFile(path.join(targetDir, '.env'), envFile({ mode, domain, appUrl, imageRegistry, imageTag, superadminEmail, superadminName, smtpConfigured, smtpHost, smtpPort, smtpUser, smtpPassword, mailFrom, caddyAcmeEmail, postgresPassword, sessionSecret, appEncryptionKey, bootstrapPassword }))
  await fs.writeFile(path.join(targetDir, 'docker-compose.yml'), mode === 'managed-simple' ? composeForManagedSimple() : composeForExistingInfra())
  if (mode === 'managed-simple') {
    await fs.writeFile(path.join(targetDir, 'Caddyfile'), caddyfile(domain))
  }
  await fs.writeFile(path.join(targetDir, 'SETUP_NOTES.txt'), setupNotes(mode, bootstrapPassword, targetDir, appUrl, smtpConfigured))

  console.log(setupNotes(mode, bootstrapPassword, targetDir, appUrl, smtpConfigured))

  const runCompose = await confirm({ message: 'Run docker compose setup now?', default: false })
  if (runCompose) {
    await runInstallerCommands(mode, targetDir, appUrl)
    if (mode === 'managed-simple') {
      console.log(`\nsally_ setup completed. Open: ${appUrl}`)
    } else {
      console.log(`\nsally_ setup completed.`)
      console.log(`- Web is listening on: http://127.0.0.1:3000`)
      console.log(`- API is listening on: http://127.0.0.1:4000`)
      console.log(`- Public app URL after your reverse proxy / TLS is configured: ${appUrl}`)
    }
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error))
  process.exit(1)
})
